[OrdinaryDiffEq]
PrecompileAutoSpecialize = false
PrecompileAutoSwitch = false
PrecompileDefaultSpecialize = true
PrecompileFunctionWrapperSpecialize = false
PrecompileLowStorage = true
PrecompileNoSpecialize = false
PrecompileNonStiff = true
PrecompileStiff = false
